In [1]:
import torch

#从list创建
torch.tensor([1, 2]), torch.tensor([[1, 2], [3, 4]])

(tensor([1, 2]),
 tensor([[1, 2],
         [3, 4]]))

In [2]:
import numpy as np

#从numpy创建
torch.from_numpy(np.array([1, 2]))

tensor([1, 2])

In [3]:
#全1填充
print(torch.ones(2, 3))

#全0填充
print(torch.zeros(2, 3))

#full填充
print(torch.full([2, 3], 7))

#对角矩阵
print(torch.eye(3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[7, 7, 7],
        [7, 7, 7]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [4]:
#创建但不初始化
print(torch.empty(2, 3))

#标准正态分布
print(torch.randn(2, 3))

#0-1均匀分布
print(torch.rand(2, 3))

#1-9的整数均匀分布
print(torch.randint(1, 10, [2, 3]))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[-1.0020,  0.6792, -1.2098],
        [-2.6513, -1.4667, -0.0785]])
tensor([[0.8533, 0.4675, 0.9124],
        [0.3488, 0.5822, 0.0545]])
tensor([[2, 9, 7],
        [8, 6, 3]])


In [5]:
#自增数列,0到9,步长是1
print(torch.arange(0, 10, 2))

#等差数列,0到10,4个数
print(torch.linspace(0, 10, 4))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  3.3333,  6.6667, 10.0000])


In [6]:
#指定类型的创建
torch.FloatTensor([1, 2]), torch.LongTensor([1, 2])

(tensor([1., 2.]), tensor([1, 2]))

In [7]:
#获取数据类型
torch.randn(2, 3).dtype

torch.float32

In [8]:
#转换数据类型
torch.randn(2, 3).to(torch.float64).dtype

torch.float64