In [1]:
import torch

#测试数据
a = torch.FloatTensor([[0, 1, 2], [3, 4, 5]])
b = torch.FloatTensor([0, 1, 2])

a, b

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]))

In [2]:
#四则运算
print(a + b)
print(a - b)
print(a * b)
print(a / b)

tensor([[0., 2., 4.],
        [3., 5., 7.]])
tensor([[0., 0., 0.],
        [3., 3., 3.]])
tensor([[ 0.,  1.,  4.],
        [ 0.,  4., 10.]])
tensor([[   nan, 1.0000, 1.0000],
        [   inf, 4.0000, 2.5000]])


In [3]:
#矩阵乘法
print(a @ b)
print(a.matmul(b))

#计算过程
0 * 0 + 1 * 1 + 2 * 2, 0 * 3 + 1 * 4 + 2 * 5

tensor([ 5., 14.])
tensor([ 5., 14.])


(5, 14)

In [4]:
#指数,对数运算

#求指数
print(a**2)

#开根号
print(a**0.5)

#求e的n次方
print(a.exp())

#以e为底,求对数
print(a.log())

#以2为底,求对数
print(a.log2())

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])
tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])
tensor([[  1.0000,   2.7183,   7.3891],
        [ 20.0855,  54.5981, 148.4132]])
tensor([[  -inf, 0.0000, 0.6931],
        [1.0986, 1.3863, 1.6094]])
tensor([[  -inf, 0.0000, 1.0000],
        [1.5850, 2.0000, 2.3219]])


In [5]:
#裁剪,限制数据的上下限
a.clamp(2, 4)

tensor([[2., 2., 2.],
        [3., 4., 4.]])

In [6]:
#逻辑运算

#大于
print(a > b)

#小于
print(a < b)

#等于
print(a == b)

#不等于
print(a != b)

tensor([[False, False, False],
        [ True,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[ True,  True,  True],
        [False, False, False]])
tensor([[False, False, False],
        [ True,  True,  True]])


In [7]:
#四舍五入
c = torch.FloatTensor([3.14])

#向下取整
print(c.floor())

#向上取整
print(c.ceil())

#四舍五入
print(c.round())

tensor([3.])
tensor([4.])
tensor([3.])
